### ISSUE TITLE
Rendering order

### ISSUE THREAD

**Issue by Tornadoally** [Redninja106/simulationframework#39]
It would be nice to be able to configure the canvas to draw elements to an id and render them in that order. This would be helpful so you don't always have to draw back to front. For example one could do

canvas.SetDrawingID(0);
canvas.DrawText(text, pos);
Vector2 rectSize = canvas.MeasureText(text);
canvas.SetDrawingID(-1);
canvas.DrawRect(pos, rectSize);

I've had quite a few cases where a certain size of one element is based on the element which renders on top of it and this feature would make the process a lot easier.

**Comment by Redninja106** [comment]
Unfortunately the drawing has to be done back to front as shapes are drawn on top of one another. If you really need something like this you can create a texture the same size as the canvas, render to that, then render it to the canvas. Though this shouldn't be necessary since it's usually straightforward to figure out the size of a shape before you draw it.
